-- This can be used to create tables for something like a test database by running:
-- psql -U dunder_mifflin -d knex-practice-test -f ./blogful-scripts/create.blogful.sql

CREATE TABLE noteful_folders (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL
);

CREATE TABLE noteful_notes (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    content TEST,
    date_commented TIMESTAMPTZ DEFAULT now() NOT NULL,
    folder_id INTEGER
            REFERENCES blogful_articles(id) ON DELETE CASCADE NOT NULL,
);